img_shape: 256

model:
  name: "auto-encoder"
  latent_dim: 1024
  final_activation: "tanh"
  encoder:
    conv_channels: [ 64, 128, 128, 256, 256, 512 ]
    kernels: [ 7, 3, 1, 3, 1, 3 ]
    strides: [ 1, 1, 2, 1, 2, 1 ]
    norm: [ true, true, false, true, false, true]
    activation: [ 'relu', 'relu', 'relu', 'relu', 'relu', 'relu' ]
    fc:
      - 1024
  
  decoder:
    conv_channels: [ 512, 256, 256, 128, 128, 64, 3 ]
    kernels: [ 3, 1, 3, 1, 3, 7, 4 ]
    strides: [ 1, 2, 1, 2, 1, 1, 1 ]
    norm: [ true, false, true, false, true, true, true]
    activation: [ 'relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'tanh' ]