img_shape: 32
random_seed: 7
generate_samples: true
data:
  clz: "CIFAR10Dataset"
  num_classes: 10
  batch_size: 256
  num_workers: 4
  # data_prefix_path: "REPLACE_WITH_DATA_PATH"
  # val_data_prefix_path: "REPLACE_WITH_DATA_PATH"
  augmentation_probability: 0.2
  train_size: 0.8

train:
  optim: 'Adam'
  optim_params:
    lr: 0.001
    # betas: [0.9, 0.999]
    amsgrad: true
    weight_decay: 0.0001
  epochs: 50
  # num_train_steps: 1000
  # num_train_steps: 10
  scheduler:
    eta_min: 0.000001
  kl_loss_weight: 0.2
  loss_fn: null

model:
  name: "vq-vae"
  enable_perceptual: false
  export_path: "/tmp/model_cifar.pt"
  # Conv formula x = [(i - w + 2*p)/s] + 1
  # Conv transpose formula i = (x-1)*s + w - 2*p
  encoder:
    layers:
      - name: 'conv2d'
        activation: 'ReLU'
        param:
          in_channels: 3
          out_channels: 64
          kernel_size: 4
          stride: 2
          padding: 1

      - name: 'conv2d'
        activation: 'ReLU'
        param:
          in_channels: 64
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 1
      
      - name: 'conv2d'
        param:
          in_channels: 128
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 1

      - name: 'resnet'
        param:
          in_channels: 128
          num_hiddens: 128
          num_residual_layers: 2
          num_residual_hiddens: 32

  pre_codebook:
    param:
      in_channels: 128
      out_channels: 64
      kernel_size: 1
      stride: 1
      padding: 0
    # 32
  codebook:
    k: 512 
    dim: 64
    commitment_coefficient: 0.25

  # post_codebook:
  #   param:
  #     in_channels: 64
  #     out_channels: 128
  #     kernel_size: 1
  #     stride: 1
  #     padding: 0

  decoder:
    layers:
      - name: 'conv2d'
        param:
          in_channels: 64
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 1

      - name: 'resnet'
        param:
          in_channels: 128
          num_hiddens: 128
          num_residual_layers: 2
          num_residual_hiddens: 32

      - name: 'conv2d_transpose'
        activation: 'ReLU'
        param:
          in_channels: 128
          out_channels: 64
          kernel_size: 4
          stride: 2
          padding: 1

      - name: 'conv2d_transpose'
        param:
          in_channels: 64
          out_channels: 3
          kernel_size: 4
          stride: 2
          padding: 1
