img_shape: 256
random_seed: 7
generate_samples: true
data:
  clz: "COCODataset"
  num_classes: 1024
  batch_size: 32
  # batch_size: 8
  num_workers: 10
  # data_prefix_path: "REPLACE_WITH_DATA_PATH"
  # val_data_prefix_path: "REPLACE_WITH_DATA_PATH"
  data_prefix_path: "/Users/deepak.dhull/practice/data/val2017"
  val_data_prefix_path: "/Users/deepak.dhull/practice/data/val2017"
  augmentation_probability: 0.2
  train_size: 0.8

train:
  optim: 'Adam'
  optim_params:
    lr: 0.0002
    betas: [0.9, 0.999]
    amsgrad: true
    weight_decay: 0.0001
  epochs: 50
  num_train_steps: 250000
  # num_train_steps: 10
  scheduler:
    eta_min: 0.000001
  kl_loss_weight: 0.2
  loss_fn: null

model:
  name: "vq-vae"
  enable_perceptual: true
  export_path: "/tmp/model.pt"
  # Conv formula x = [(i - w + 2*p)/s] + 1
  # Conv transpose formula i = (x-1)*s + w - 2*p
  encoder:
    layers:
    # 128
      - name: 'conv2d'
        param:
          in_channels: 3
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 1
    # 64
      - name: 'conv2d'
        param:
          in_channels: 128
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 1
    # 32
      - name: 'resnet'
        repeat: 2
        dim: 128
    # 32
  codebook:
    k: 1024
    dim: 128
    commitment_coefficient: 0.5

  decoder:
    layers:
      - name: 'resnet'
        repeat: 2
        dim: 128
      # 32
      - name: 'conv2d_transpose'
        param:
          in_channels: 128
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 1
      # 64
      - name: 'conv2d_transpose'
        param:
          in_channels: 128
          out_channels: 3
          kernel_size: 4
          stride: 2
          padding: 1
      # 128